name: Build APK (auto-zip)

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Ensure tools
        run: |
          sudo apt-get update
          sudo apt-get install -y unzip findutils

      - name: Locate ZIP (any name)
        id: findzip
        run: |
          set -e
          ZIP="$(ls -1 *.zip 2>/dev/null | head -n 1 || true)"
          if [ -z "$ZIP" ]; then
            echo "No se encontró ningún .zip en la raíz del repo"
            exit 1
          fi
          echo "ZIP=$ZIP" >> $GITHUB_ENV
          echo "Usando ZIP: $ZIP"

      - name: Unzip project
        run: unzip -o "$ZIP" -d .

      - name: Detect project dir (contains app/build.gradle)
        id: detectdir
        run: |
          set -e
          DIR="$(dirname "$(find . -type f -path '*/app/build.gradle' | head -n 1)")"
          if [ -z "$DIR" ]; then
            echo "No se encontró app/build.gradle tras descomprimir"
            find . -maxdepth 3 -type f -name 'build.gradle' -o -name 'settings.gradle' | sed 's/^/  - /'
            exit 1
          fi
          echo "PROJECT_DIR=$DIR" >> $GITHUB_ENV
          echo "Proyecto: $DIR"

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Accept licenses & install SDKs
        run: |
          yes | sdkmanager --licenses
          sdkmanager "platforms;android-35" "build-tools;35.0.0" "platform-tools"

      - name: Build with Gradle (no wrapper)
        uses: gradle/gradle-build-action@v3
        with:
          gradle-version: 8.9
          build-root-directory: ${{ env.PROJECT_DIR }}
          arguments: assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug.apk
          path: ${{ env.PROJECT_DIR }}/app/build/outputs/apk/debug/app-debug.apk
